server:
  port: 8081

spring:
  application:
    name: store-admin
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin123!@#
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    database: mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/delivery?useUnicode=true&characterEncoding=UTF8&autoReconnect=true&serverTimezone=Asia/Seoul
    username: root
    password: root
